### ISSUE TITLE
Resizing pane

### ISSUE THREAD

**Issue by isaacengel** [Aerijo/atom-pdf-view-plus#6]
When in split view, the size of the pane with the pdf file can be increased but not reduced.

EDIT: it seems to happen only when opening the file automatically from the `latex` package, when introducing these changes https://github.com/thomasjo/atom-latex/pull/533

**Comment by Aerijo** [comment]
Yup, see https://github.com/atom/atom/pull/19862

**Comment by isaacengel** [comment]
Cool, that was it, thanks!
